{
 "title": "Docker_OEG",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": { "query": "buckets()" } },
   {
    "name": "container",
    "query": {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\n  |> keyValues(keyColumns: [\"container_name\"])\n  |> group()\n  |> keep(columns: [\"container_name\"])\n  |> distinct(column: \"container_name\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Estado Dockers",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "union(\n  tables: [\n    from(bucket: \"${bucket}\")\n      |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n      |> filter(fn: (r) => r[\"_measurement\"] == \"docker\")\n      |> filter(fn: (r) => r[\"_field\"] == \"n_containers_running\")\n      |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n      |> map(fn: (r) => ({ _value: r._value, metric: \"Contenedores Activos\" })),\n    from(bucket: \"${bucket}\")\n      |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n      |> filter(fn: (r) => r[\"_measurement\"] == \"docker\")\n      |> filter(fn: (r) => r[\"_field\"] == \"n_containers_stopped\")\n      |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n      |> map(fn: (r) => ({ _value: r._value, metric: \"Contenedores Parados\" })),\n    from(bucket: \"${bucket}\")\n      |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n      |> filter(fn: (r) => r[\"_measurement\"] == \"docker\")\n      |> filter(fn: (r) => r[\"_field\"] == \"n_containers_paused\")\n      |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n      |> map(fn: (r) => ({ _value: r._value, metric: \"Contenedores Pausados\" })),\n    from(bucket: \"${bucket}\")\n      |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n      |> filter(fn: (r) => r[\"_measurement\"] == \"docker\")\n      |> filter(fn: (r) => r[\"_field\"] == \"n_images\")\n      |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n      |> map(fn: (r) => ({ _value: r._value, metric: \"Imágenes Disponibles\" }))\n  ]\n)\n  |> rename(columns: { _value: \"Valor\", metric: \"Métrica\" })\n  |> group(columns: [\"Métrica\"])\n"
    }
   ]
  },
  {
   "title": "CPU_Docker",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\n  |> filter(fn: (r) => r[\"container_name\"] =~ /${container:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memoria_Docker",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\n  |> filter(fn: (r) => r[\"container_name\"] =~ /${container:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Disco_Docker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_blkio\")\n  |> filter(fn: (r) => r[\"_field\"] == \"io_service_bytes_recursive_read\" or r[\"_field\"] == \"io_service_bytes_recursive_write\")\n  |> filter(fn: (r) => r[\"container_name\"] =~ /${container:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Consumo_Red_Docker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_net\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rx_bytes\" or r[\"_field\"] == \"tx_bytes\")\n  |> filter(fn: (r) => r[\"container_name\"] =~ /${container:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  }
 ]
}