{
 "title": "Servidores_OEG",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": { "query": "buckets()" } },
   {
    "name": "host",
    "query": {
     "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(bucket: \"${bucket}\", tag: \"host\")\n"
    }
   },
   {
    "name": "Mongo",
    "query": {
     "query": "import \"influxdata/influxdb/v1\"\n\nv1.tagValues(\n  bucket: \"${bucket}\",\n  tag: \"has_mongo\"\n)\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Porcentaje_CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] =~ /${host:regex}/)\n  |> filter(fn: (r) => r[\"has_mongo\"] =~ /${Mongo:regex}/)\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_idle\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: 100.0 - r._value }))\n  |> yield(name: \"mean\")\n"
    },
    {}
   ]
  },
  {
   "title": "Porcentaje_Disco",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used\" or r[\"_field\"] == \"free\")  // Trabaja con valores absolutos\n  |> filter(fn: (r) => r[\"host\"] =~ /${host:regex}/)\n  |> filter(fn: (r) => r[\"has_mongo\"] =~ /${Mongo:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)  // Suma los valores por partición\n  |> group(columns: [\"host\"])  // Agrupa por servidor\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")  // Reorganiza los campos en columnas\n  |> map(fn: (r) => ({\n        _time: r._time,\n        _value: float(v: r[\"used\"]) / (float(v: r[\"used\"]) + float(v: r[\"free\"])) * 100.0,\n        host: r.host\n    }))\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])  // Mantén solo las columnas esenciales\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Porcentaje_Memoria",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"free\" or r[\"_field\"] == \"used\")\n  |> filter(fn: (r) => r[\"host\"] =~ /${host:regex}/)\n  |> filter(fn: (r) => r[\"has_mongo\"] =~ /${Mongo:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n        _time: r._time,\n        _value: float(v: r[\"used\"]) / (float(v: r[\"free\"]) + float(v: r[\"used\"])) * 100.0, // Asegura que todos los valores sean float\n        host: r.host\n      }))\n  |> yield(name: \"mean\")\n"
    }
   ]
  }
 ]
}