{
 "title": "Servicios_OEG",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": { "query": "buckets()" } }
  ]
 },
 "panels": [
  {
   "title": "Estado de los Contendores Docker",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "  from(bucket: \"${bucket}\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"docker_gen\")  // Filtra los datos de contenedores generales\n    |> filter(fn: (r) => r[\"_field\"] == \"message\" or r[\"_field\"] == \"status_code\" or r[\"_field\"] == \"keywords\")\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")  // Reorganiza los datos\n    |> group()  // Agrupa los datos (generalmente necesario antes de `sort`)\n    |> sort(columns: [\"_time\"], desc: true)  // Ordena por tiempo de forma descendente\n    |> unique(column: \"nombre\")  // Obtén solo el último registro para cada contenedor basado en \"nombre\"\n    |> keep(columns: [\"_time\", \"nombre\", \"keywords\", \"status_code\", \"message\"])  // Mantén solo las columnas necesarias\n"
    }
   ]
  },
  {
   "title": "Estado de los Servicios Web",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"servicio_gen\")  // Filtra los datos de servicios generales\n  |> filter(fn: (r) => r[\"_field\"] == \"message\" or r[\"_field\"] == \"status_code\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")  // Reorganiza los datos\n  |> group()  // Agrupa los datos (generalmente es necesario para operaciones como `sort`)\n  |> sort(columns: [\"_time\"], desc: true)  // Ordena por tiempo de forma descendente\n  |> unique(column: \"url\")  // Obtén solo el último registro para cada URL\n  |> keep(columns: [\"_time\", \"url\", \"nombre\", \"keywords\", \"status_code\", \"message\",\"servidor\",\"proyecto\",\"maquina_virtual\",\"administrador\"])  // Mantén solo las columnas necesarias\n"
    }
   ]
  },
  {
   "title": "Alertas_Servicios",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"DatosPrueba\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) // Rango de tiempo dinámico del panel\n  |> filter(fn: (r) => r[\"_measurement\"] == \"servicio_gen\") // Filtra los datos de 'servicio_gen'\n  |> filter(fn: (r) => r[\"_field\"] == \"status_code\") // Filtro para los códigos de estado\n  //|> filter(fn: (r) => r[\"url\"] == \"http://localhost:27017/\")\n  //|> filter(fn: (r) => r[\"nombre\"] == \"prueba/403\")\n  //|> filter(fn: (r) => r[\"servidor\"] == \"servidor_1\")\n  //|> filter(fn: (r) => r[\"proyecto\"] == \"proyecto_B\")\n  //|> filter(fn: (r) => r[\"keywords\"] == \"api\")\n  //|> filter(fn: (r) => r[\"maquina_virtual\"] == \"VM_1\")\n  //|> filter(fn: (r) => r[\"administrador\"] == \"admin_3\")\n\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\") // Reestructura los datos para 'status_code'\n  |> keep(columns: [\"_time\", \"url\", \"status_code\"]) // Conserva solo las columnas necesarias\n"
    }
   ]
  },
  {
   "title": "Alertas_Docker",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"DatosPrueba\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) // Rango de tiempo dinámico del panel\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_gen\") // Filtra los datos de 'servicio_gen'\n  |> filter(fn: (r) => r[\"_field\"] == \"status_code\") // Filtro para los códigos de estado\n  \n  //|> filter(fn: (r) => r[\"nombre\"] == \"alpine\")\n  //|> filter(fn: (r) => r[\"keywords\"] == \"database\")\n\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\") // Reestructura los datos para 'status_code'\n  |> keep(columns: [\"_time\", \"nombre\", \"status_code\"]) // Conserva solo las columnas necesarias\n"
    }
   ]
  }
 ]
}